// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user-service/proto/user/user_service.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 组织信息DTO
type OrganizationDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	OwnerCode     int64                  `protobuf:"varint,5,opt,name=owner_code,json=ownerCode,proto3" json:"owner_code,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Code          string                 `protobuf:"bytes,8,opt,name=code,proto3" json:"code,omitempty"`
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,10,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,11,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,12,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationDTO) Reset() {
	*x = OrganizationDTO{}
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDTO) ProtoMessage() {}

func (x *OrganizationDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDTO.ProtoReflect.Descriptor instead.
func (*OrganizationDTO) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OrganizationDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationDTO) GetOwnerCode() int64 {
	if x != nil {
		return x.OwnerCode
	}
	return 0
}

func (x *OrganizationDTO) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *OrganizationDTO) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *OrganizationDTO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OrganizationDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrganizationDTO) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *OrganizationDTO) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *OrganizationDTO) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

// 获取组织列表请求
type GetOrgListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgListRequest) Reset() {
	*x = GetOrgListRequest{}
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListRequest) ProtoMessage() {}

func (x *GetOrgListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListRequest.ProtoReflect.Descriptor instead.
func (*GetOrgListRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrgListRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

// 获取组织列表响应
type GetOrgListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationList []*OrganizationDTO     `protobuf:"bytes,1,rep,name=organization_list,json=organizationList,proto3" json:"organization_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrgListResponse) Reset() {
	*x = GetOrgListResponse{}
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListResponse) ProtoMessage() {}

func (x *GetOrgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListResponse.ProtoReflect.Descriptor instead.
func (*GetOrgListResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrgListResponse) GetOrganizationList() []*OrganizationDTO {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

var File_user_service_proto_user_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_user_user_service_proto_rawDesc = "" +
	"\n" +
	"*user-service/proto/user/user_service.proto\x12\x0fuser.service.v1\"\xbd\x02\n" +
	"\x0fOrganizationDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"owner_code\x18\x05 \x01(\x03R\townerCode\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x12\n" +
	"\x04code\x18\b \x01(\tR\x04code\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\n" +
	" \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\v \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\f \x01(\x05R\x04area\"0\n" +
	"\x11GetOrgListRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\"c\n" +
	"\x12GetOrgListResponse\x12M\n" +
	"\x11organization_list\x18\x01 \x03(\v2 .user.service.v1.OrganizationDTOR\x10organizationList2v\n" +
	"\vUserService\x12g\n" +
	"\x1aGetOrganizationsByMemberId\x12\".user.service.v1.GetOrgListRequest\x1a#.user.service.v1.GetOrgListResponse\"\x00B:Z8github.com/Wafer233/msproject-be/user-service/proto/userb\x06proto3"

var (
	file_user_service_proto_user_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_user_user_service_proto_rawDescData []byte
)

func file_user_service_proto_user_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_user_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_user_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_user_user_service_proto_rawDesc), len(file_user_service_proto_user_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_user_user_service_proto_rawDescData
}

var file_user_service_proto_user_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_service_proto_user_user_service_proto_goTypes = []any{
	(*OrganizationDTO)(nil),    // 0: user.service.v1.OrganizationDTO
	(*GetOrgListRequest)(nil),  // 1: user.service.v1.GetOrgListRequest
	(*GetOrgListResponse)(nil), // 2: user.service.v1.GetOrgListResponse
}
var file_user_service_proto_user_user_service_proto_depIdxs = []int32{
	0, // 0: user.service.v1.GetOrgListResponse.organization_list:type_name -> user.service.v1.OrganizationDTO
	1, // 1: user.service.v1.UserService.GetOrganizationsByMemberId:input_type -> user.service.v1.GetOrgListRequest
	2, // 2: user.service.v1.UserService.GetOrganizationsByMemberId:output_type -> user.service.v1.GetOrgListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_service_proto_user_user_service_proto_init() }
func file_user_service_proto_user_user_service_proto_init() {
	if File_user_service_proto_user_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_user_user_service_proto_rawDesc), len(file_user_service_proto_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_user_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_user_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_proto_user_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto_user_user_service_proto = out.File
	file_user_service_proto_user_user_service_proto_goTypes = nil
	file_user_service_proto_user_user_service_proto_depIdxs = nil
}
