// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/organization/organization.proto

package organization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrgListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemId         int64                  `protobuf:"varint,1,opt,name=memId,proto3" json:"memId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgListMessage) Reset() {
	*x = GetOrgListMessage{}
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListMessage) ProtoMessage() {}

func (x *GetOrgListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListMessage.ProtoReflect.Descriptor instead.
func (*GetOrgListMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_organization_organization_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrgListMessage) GetMemId() int64 {
	if x != nil {
		return x.MemId
	}
	return 0
}

type Organization struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile           string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Realname         string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	Account          string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime    string                 `protobuf:"bytes,7,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	Address          string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province         int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City             int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area             int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Email            string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	Code             string                 `protobuf:"bytes,13,opt,name=code,proto3" json:"code,omitempty"`
	CreateTime       string                 `protobuf:"bytes,14,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,15,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Avatar           string                 `protobuf:"bytes,16,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_organization_organization_proto_rawDescGZIP(), []int{1}
}

func (x *Organization) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Organization) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *Organization) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Organization) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Organization) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *Organization) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Organization) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *Organization) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *Organization) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Organization) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Organization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Organization) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Organization) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *Organization) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type GetOrgListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationList []*Organization        `protobuf:"bytes,1,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrgListResponse) Reset() {
	*x = GetOrgListResponse{}
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListResponse) ProtoMessage() {}

func (x *GetOrgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_organization_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListResponse.ProtoReflect.Descriptor instead.
func (*GetOrgListResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_organization_organization_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrgListResponse) GetOrganizationList() []*Organization {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

var File_api_gateway_proto_organization_organization_proto protoreflect.FileDescriptor

const file_api_gateway_proto_organization_organization_proto_rawDesc = "" +
	"\n" +
	"1api-gateway/proto/organization/organization.proto\x12\x17organization.service.v1\")\n" +
	"\x11GetOrgListMessage\x12\x14\n" +
	"\x05memId\x18\x01 \x01(\x03R\x05memId\"\xaa\x03\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12$\n" +
	"\rlastLoginTime\x18\a \x01(\tR\rlastLoginTime\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\r \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"createTime\x18\x0e \x01(\tR\n" +
	"createTime\x12*\n" +
	"\x10organizationCode\x18\x0f \x01(\tR\x10organizationCode\x12\x16\n" +
	"\x06avatar\x18\x10 \x01(\tR\x06avatar\"g\n" +
	"\x12GetOrgListResponse\x12Q\n" +
	"\x10organizationList\x18\x01 \x03(\v2%.organization.service.v1.OrganizationR\x10organizationList2~\n" +
	"\x13OrganizationService\x12g\n" +
	"\n" +
	"GetOrgList\x12*.organization.service.v1.GetOrgListMessage\x1a+.organization.service.v1.GetOrgListResponse\"\x00BAZ?github.com/Wafer233/msproject-be/api-gateway/proto/organizationb\x06proto3"

var (
	file_api_gateway_proto_organization_organization_proto_rawDescOnce sync.Once
	file_api_gateway_proto_organization_organization_proto_rawDescData []byte
)

func file_api_gateway_proto_organization_organization_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_organization_organization_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_organization_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_organization_organization_proto_rawDesc), len(file_api_gateway_proto_organization_organization_proto_rawDesc)))
	})
	return file_api_gateway_proto_organization_organization_proto_rawDescData
}

var file_api_gateway_proto_organization_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_proto_organization_organization_proto_goTypes = []any{
	(*GetOrgListMessage)(nil),  // 0: organization.service.v1.GetOrgListMessage
	(*Organization)(nil),       // 1: organization.service.v1.Organization
	(*GetOrgListResponse)(nil), // 2: organization.service.v1.GetOrgListResponse
}
var file_api_gateway_proto_organization_organization_proto_depIdxs = []int32{
	1, // 0: organization.service.v1.GetOrgListResponse.organizationList:type_name -> organization.service.v1.Organization
	0, // 1: organization.service.v1.OrganizationService.GetOrgList:input_type -> organization.service.v1.GetOrgListMessage
	2, // 2: organization.service.v1.OrganizationService.GetOrgList:output_type -> organization.service.v1.GetOrgListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_organization_organization_proto_init() }
func file_api_gateway_proto_organization_organization_proto_init() {
	if File_api_gateway_proto_organization_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_organization_organization_proto_rawDesc), len(file_api_gateway_proto_organization_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_organization_organization_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_organization_organization_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_organization_organization_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_organization_organization_proto = out.File
	file_api_gateway_proto_organization_organization_proto_goTypes = nil
	file_api_gateway_proto_organization_organization_proto_depIdxs = nil
}
