version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    container_name: ms-mysql
    networks:
      - ms-network

  redis:
    image: 'redis:latest'
    container_name: ms-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - ms-network




networks:
  ms-network:
    name: ms-network