version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    container_name: ms-mysql
    networks:
      - ms-network

  redis:
    image: 'redis:latest'
    container_name: ms-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - ms-network

  prometheus:
    image: 'prom/prometheus:latest'
    container_name: ms-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./deploy/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - ms-network


networks:
  ms-network:
    name: ms-network