// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/login/login.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------- GetCaptcha ----------------------------
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaptchaRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type GetCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse) Reset() {
	*x = GetCaptchaResponse{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse) ProtoMessage() {}

func (x *GetCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// ---------------------------- Register ----------------------------
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Captcha       string                 `protobuf:"bytes,5,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{3}
}

// ---------------------------- Login ----------------------------
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Member           *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	OrganizationList []*Organization        `protobuf:"bytes,2,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	TokenList        *Token                 `protobuf:"bytes,3,opt,name=tokenList,proto3" json:"tokenList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *LoginResponse) GetOrganizationList() []*Organization {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

func (x *LoginResponse) GetTokenList() *Token {
	if x != nil {
		return x.TokenList
	}
	return nil
}

// ---------------------------- TokenVerify ----------------------------
type TokenVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyRequest) Reset() {
	*x = TokenVerifyRequest{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyRequest) ProtoMessage() {}

func (x *TokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*TokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{6}
}

func (x *TokenVerifyRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *TokenVerifyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenVerifyRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type TokenVerifyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Member           *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	OrganizationList []*Organization        `protobuf:"bytes,2,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	TokenList        *Token                 `protobuf:"bytes,3,opt,name=tokenList,proto3" json:"tokenList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenVerifyResponse) Reset() {
	*x = TokenVerifyResponse{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyResponse) ProtoMessage() {}

func (x *TokenVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyResponse.ProtoReflect.Descriptor instead.
func (*TokenVerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{7}
}

func (x *TokenVerifyResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *TokenVerifyResponse) GetOrganizationList() []*Organization {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

func (x *TokenVerifyResponse) GetTokenList() *Token {
	if x != nil {
		return x.TokenList
	}
	return nil
}

// ---------------------------- GetOrgList ----------------------------
type GetOrgListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrgListRequest) Reset() {
	*x = GetOrgListRequest{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListRequest) ProtoMessage() {}

func (x *GetOrgListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListRequest.ProtoReflect.Descriptor instead.
func (*GetOrgListRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrgListRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type GetOrgListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationList []*Organization        `protobuf:"bytes,1,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOrgListResponse) Reset() {
	*x = GetOrgListResponse{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrgListResponse) ProtoMessage() {}

func (x *GetOrgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrgListResponse.ProtoReflect.Descriptor instead.
func (*GetOrgListResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrgListResponse) GetOrganizationList() []*Organization {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

// ---------------------------- common ----------------------------
type Member struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile           string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Realname         string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	Account          string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime    string                 `protobuf:"bytes,7,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	Address          string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province         int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City             int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area             int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Email            string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	Code             string                 `protobuf:"bytes,13,opt,name=code,proto3" json:"code,omitempty"`
	CreateTime       string                 `protobuf:"bytes,14,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,15,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	Avatar           string                 `protobuf:"bytes,16,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{10}
}

func (x *Member) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Member) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Member) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *Member) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Member) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Member) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *Member) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *Member) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Member) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Member) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *Member) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberId      int64                  `protobuf:"varint,5,opt,name=memberId,proto3" json:"memberId,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Code          string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"`
	OwnerCode     string                 `protobuf:"bytes,13,opt,name=ownerCode,proto3" json:"ownerCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{11}
}

func (x *Organization) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *Organization) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Organization) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *Organization) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Organization) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *Organization) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *Organization) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *Organization) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Organization) GetOwnerCode() string {
	if x != nil {
		return x.OwnerCode
	}
	return ""
}

type Token struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	TokenType      string                 `protobuf:"bytes,3,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	AccessTokenExp int64                  `protobuf:"varint,4,opt,name=accessTokenExp,proto3" json:"accessTokenExp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_login_login_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_login_login_proto_rawDescGZIP(), []int{12}
}

func (x *Token) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Token) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *Token) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *Token) GetAccessTokenExp() int64 {
	if x != nil {
		return x.AccessTokenExp
	}
	return 0
}

var File_api_gateway_proto_login_login_proto protoreflect.FileDescriptor

const file_api_gateway_proto_login_login_proto_rawDesc = "" +
	"\n" +
	"#api-gateway/proto/login/login.proto\x12\blogin.v1\"+\n" +
	"\x11GetCaptchaRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"(\n" +
	"\x12GetCaptchaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x89\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x18\n" +
	"\acaptcha\x18\x05 \x01(\tR\acaptcha\"\x12\n" +
	"\x10RegisterResponse\"j\n" +
	"\fLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\"\xac\x01\n" +
	"\rLoginResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.login.v1.MemberR\x06member\x12B\n" +
	"\x10organizationList\x18\x02 \x03(\v2\x16.login.v1.OrganizationR\x10organizationList\x12-\n" +
	"\ttokenList\x18\x03 \x01(\v2\x0f.login.v1.TokenR\ttokenList\"p\n" +
	"\x12TokenVerifyRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\"\xb2\x01\n" +
	"\x13TokenVerifyResponse\x12(\n" +
	"\x06member\x18\x01 \x01(\v2\x10.login.v1.MemberR\x06member\x12B\n" +
	"\x10organizationList\x18\x02 \x03(\v2\x16.login.v1.OrganizationR\x10organizationList\x12-\n" +
	"\ttokenList\x18\x03 \x01(\v2\x0f.login.v1.TokenR\ttokenList\"/\n" +
	"\x11GetOrgListRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\"X\n" +
	"\x12GetOrgListResponse\x12B\n" +
	"\x10organizationList\x18\x01 \x03(\v2\x16.login.v1.OrganizationR\x10organizationList\"\xa4\x03\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12$\n" +
	"\rlastLoginTime\x18\a \x01(\tR\rlastLoginTime\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\r \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"createTime\x18\x0e \x01(\tR\n" +
	"createTime\x12*\n" +
	"\x10organizationCode\x18\x0f \x01(\tR\x10organizationCode\x12\x16\n" +
	"\x06avatar\x18\x10 \x01(\tR\x06avatar\"\xd4\x02\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmemberId\x18\x05 \x01(\x03R\bmemberId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\x12\x1c\n" +
	"\townerCode\x18\r \x01(\tR\townerCode\"\x93\x01\n" +
	"\x05Token\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\ttokenType\x18\x03 \x01(\tR\ttokenType\x12&\n" +
	"\x0eaccessTokenExp\x18\x04 \x01(\x03R\x0eaccessTokenExp2\xf3\x02\n" +
	"\fLoginService\x12I\n" +
	"\n" +
	"GetCaptcha\x12\x1b.login.v1.GetCaptchaRequest\x1a\x1c.login.v1.GetCaptchaResponse\"\x00\x12C\n" +
	"\bRegister\x12\x19.login.v1.RegisterRequest\x1a\x1a.login.v1.RegisterResponse\"\x00\x12:\n" +
	"\x05Login\x12\x16.login.v1.LoginRequest\x1a\x17.login.v1.LoginResponse\"\x00\x12L\n" +
	"\vTokenVerify\x12\x1c.login.v1.TokenVerifyRequest\x1a\x1d.login.v1.TokenVerifyResponse\"\x00\x12I\n" +
	"\n" +
	"GetOrgList\x12\x1b.login.v1.GetOrgListRequest\x1a\x1c.login.v1.GetOrgListResponse\"\x00B:Z8github.com/Wafer233/msproject-be/api-gateway/proto/loginb\x06proto3"

var (
	file_api_gateway_proto_login_login_proto_rawDescOnce sync.Once
	file_api_gateway_proto_login_login_proto_rawDescData []byte
)

func file_api_gateway_proto_login_login_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_login_login_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_login_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_login_login_proto_rawDesc), len(file_api_gateway_proto_login_login_proto_rawDesc)))
	})
	return file_api_gateway_proto_login_login_proto_rawDescData
}

var file_api_gateway_proto_login_login_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_gateway_proto_login_login_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),   // 0: login.v1.GetCaptchaRequest
	(*GetCaptchaResponse)(nil),  // 1: login.v1.GetCaptchaResponse
	(*RegisterRequest)(nil),     // 2: login.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 3: login.v1.RegisterResponse
	(*LoginRequest)(nil),        // 4: login.v1.LoginRequest
	(*LoginResponse)(nil),       // 5: login.v1.LoginResponse
	(*TokenVerifyRequest)(nil),  // 6: login.v1.TokenVerifyRequest
	(*TokenVerifyResponse)(nil), // 7: login.v1.TokenVerifyResponse
	(*GetOrgListRequest)(nil),   // 8: login.v1.GetOrgListRequest
	(*GetOrgListResponse)(nil),  // 9: login.v1.GetOrgListResponse
	(*Member)(nil),              // 10: login.v1.Member
	(*Organization)(nil),        // 11: login.v1.Organization
	(*Token)(nil),               // 12: login.v1.Token
}
var file_api_gateway_proto_login_login_proto_depIdxs = []int32{
	10, // 0: login.v1.LoginResponse.member:type_name -> login.v1.Member
	11, // 1: login.v1.LoginResponse.organizationList:type_name -> login.v1.Organization
	12, // 2: login.v1.LoginResponse.tokenList:type_name -> login.v1.Token
	10, // 3: login.v1.TokenVerifyResponse.member:type_name -> login.v1.Member
	11, // 4: login.v1.TokenVerifyResponse.organizationList:type_name -> login.v1.Organization
	12, // 5: login.v1.TokenVerifyResponse.tokenList:type_name -> login.v1.Token
	11, // 6: login.v1.GetOrgListResponse.organizationList:type_name -> login.v1.Organization
	0,  // 7: login.v1.LoginService.GetCaptcha:input_type -> login.v1.GetCaptchaRequest
	2,  // 8: login.v1.LoginService.Register:input_type -> login.v1.RegisterRequest
	4,  // 9: login.v1.LoginService.Login:input_type -> login.v1.LoginRequest
	6,  // 10: login.v1.LoginService.TokenVerify:input_type -> login.v1.TokenVerifyRequest
	8,  // 11: login.v1.LoginService.GetOrgList:input_type -> login.v1.GetOrgListRequest
	1,  // 12: login.v1.LoginService.GetCaptcha:output_type -> login.v1.GetCaptchaResponse
	3,  // 13: login.v1.LoginService.Register:output_type -> login.v1.RegisterResponse
	5,  // 14: login.v1.LoginService.Login:output_type -> login.v1.LoginResponse
	7,  // 15: login.v1.LoginService.TokenVerify:output_type -> login.v1.TokenVerifyResponse
	9,  // 16: login.v1.LoginService.GetOrgList:output_type -> login.v1.GetOrgListResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_login_login_proto_init() }
func file_api_gateway_proto_login_login_proto_init() {
	if File_api_gateway_proto_login_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_login_login_proto_rawDesc), len(file_api_gateway_proto_login_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_login_login_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_login_login_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_login_login_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_login_login_proto = out.File
	file_api_gateway_proto_login_login_proto_goTypes = nil
	file_api_gateway_proto_login_login_proto_depIdxs = nil
}
