// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() *App {
	config := ProvideViperConfig()
	db := ProvideDB(config)
	menuRepository := ProvideGORMMenuRepository(db)
	menuService := ProvideDefaultMenuService(menuRepository)
	grpcServer := ProvideGrpcServer(config, menuService)
	app := &App{
		GrpcServer: grpcServer,
	}
	return app
}
