// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() *App {
	config := ProvideViperConfig()
	db := ProvideDB(config)
	menuRepo := ProvideGORMMenuRepo(db)
	indexService := ProvideDefaultIndexService(menuRepo)
	projectRepo := ProvideGORMProjectRepo(db)
	projectService := ProvideDefaultProjectService(projectRepo)
	projectGRPCHandler := ProvideProjectGRPCHandler(indexService, projectService)
	serviceRegister := ProvideServiceRegister(projectGRPCHandler)
	projectServer := ProvideProjectServer(config, serviceRegister)
	app := &App{
		GrpcServer: projectServer,
	}
	return app
}
