// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user-service/proto/auth/auth_service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Password2     string                 `protobuf:"bytes,4,opt,name=password2,proto3" json:"password2,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Captcha       string                 `protobuf:"bytes,6,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetPassword2() string {
	if x != nil {
		return x.Password2
	}
	return ""
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type MemberDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime int64                  `protobuf:"varint,6,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberDTO) Reset() {
	*x = MemberDTO{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberDTO) ProtoMessage() {}

func (x *MemberDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberDTO.ProtoReflect.Descriptor instead.
func (*MemberDTO) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *MemberDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberDTO) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MemberDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberDTO) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MemberDTO) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberDTO) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *MemberDTO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type TokenDTO struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType      string                 `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	AccessTokenExp int64                  `protobuf:"varint,4,opt,name=access_token_exp,json=accessTokenExp,proto3" json:"access_token_exp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenDTO) Reset() {
	*x = TokenDTO{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDTO) ProtoMessage() {}

func (x *TokenDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDTO.ProtoReflect.Descriptor instead.
func (*TokenDTO) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *TokenDTO) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenDTO) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenDTO) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenDTO) GetAccessTokenExp() int64 {
	if x != nil {
		return x.AccessTokenExp
	}
	return 0
}

type OrganizationDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberId      int64                  `protobuf:"varint,5,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationDTO) Reset() {
	*x = OrganizationDTO{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDTO) ProtoMessage() {}

func (x *OrganizationDTO) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDTO.ProtoReflect.Descriptor instead.
func (*OrganizationDTO) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OrganizationDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationDTO) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *OrganizationDTO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrganizationDTO) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *OrganizationDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrganizationDTO) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *OrganizationDTO) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *OrganizationDTO) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Member           *MemberDTO             `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	TokenList        *TokenDTO              `protobuf:"bytes,2,opt,name=token_list,json=tokenList,proto3" json:"token_list,omitempty"`
	OrganizationList []*OrganizationDTO     `protobuf:"bytes,3,rep,name=organization_list,json=organizationList,proto3" json:"organization_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *LoginResponse) GetMember() *MemberDTO {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *LoginResponse) GetTokenList() *TokenDTO {
	if x != nil {
		return x.TokenList
	}
	return nil
}

func (x *LoginResponse) GetOrganizationList() []*OrganizationDTO {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

type TokenVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyRequest) Reset() {
	*x = TokenVerifyRequest{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyRequest) ProtoMessage() {}

func (x *TokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*TokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *TokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *MemberDTO             `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyResponse) Reset() {
	*x = TokenVerifyResponse{}
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyResponse) ProtoMessage() {}

func (x *TokenVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_auth_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyResponse.ProtoReflect.Descriptor instead.
func (*TokenVerifyResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_auth_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *TokenVerifyResponse) GetMember() *MemberDTO {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_user_service_proto_auth_auth_service_proto protoreflect.FileDescriptor

const file_user_service_proto_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	"*user-service/proto/auth/auth_service.proto\x12\x0fauth.service.v1\"\xa7\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1c\n" +
	"\tpassword2\x18\x04 \x01(\tR\tpassword2\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x18\n" +
	"\acaptcha\x18\x06 \x01(\tR\acaptcha\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\fLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xcf\x01\n" +
	"\tMemberDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12&\n" +
	"\x0flast_login_time\x18\x06 \x01(\x03R\rlastLoginTime\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\"\x9b\x01\n" +
	"\bTokenDTO\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12(\n" +
	"\x10access_token_exp\x18\x04 \x01(\x03R\x0eaccessTokenExp\"\xa7\x02\n" +
	"\x0fOrganizationDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmember_id\x18\x05 \x01(\x03R\bmemberId\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\"\xcc\x01\n" +
	"\rLoginResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.auth.service.v1.MemberDTOR\x06member\x128\n" +
	"\n" +
	"token_list\x18\x02 \x01(\v2\x19.auth.service.v1.TokenDTOR\ttokenList\x12M\n" +
	"\x11organization_list\x18\x03 \x03(\v2 .auth.service.v1.OrganizationDTOR\x10organizationList\"*\n" +
	"\x12TokenVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x13TokenVerifyResponse\x122\n" +
	"\x06member\x18\x01 \x01(\v2\x1a.auth.service.v1.MemberDTOR\x06member2\x86\x02\n" +
	"\vAuthService\x12Q\n" +
	"\bRegister\x12 .auth.service.v1.RegisterRequest\x1a!.auth.service.v1.RegisterResponse\"\x00\x12H\n" +
	"\x05Login\x12\x1d.auth.service.v1.LoginRequest\x1a\x1e.auth.service.v1.LoginResponse\"\x00\x12Z\n" +
	"\vTokenVerify\x12#.auth.service.v1.TokenVerifyRequest\x1a$.auth.service.v1.TokenVerifyResponse\"\x00B:Z8github.com/Wafer233/msproject-be/user-service/proto/authb\x06proto3"

var (
	file_user_service_proto_auth_auth_service_proto_rawDescOnce sync.Once
	file_user_service_proto_auth_auth_service_proto_rawDescData []byte
)

func file_user_service_proto_auth_auth_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_auth_auth_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_auth_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_auth_auth_service_proto_rawDesc), len(file_user_service_proto_auth_auth_service_proto_rawDesc)))
	})
	return file_user_service_proto_auth_auth_service_proto_rawDescData
}

var file_user_service_proto_auth_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_service_proto_auth_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),     // 0: auth.service.v1.RegisterRequest
	(*RegisterResponse)(nil),    // 1: auth.service.v1.RegisterResponse
	(*LoginRequest)(nil),        // 2: auth.service.v1.LoginRequest
	(*MemberDTO)(nil),           // 3: auth.service.v1.MemberDTO
	(*TokenDTO)(nil),            // 4: auth.service.v1.TokenDTO
	(*OrganizationDTO)(nil),     // 5: auth.service.v1.OrganizationDTO
	(*LoginResponse)(nil),       // 6: auth.service.v1.LoginResponse
	(*TokenVerifyRequest)(nil),  // 7: auth.service.v1.TokenVerifyRequest
	(*TokenVerifyResponse)(nil), // 8: auth.service.v1.TokenVerifyResponse
}
var file_user_service_proto_auth_auth_service_proto_depIdxs = []int32{
	3, // 0: auth.service.v1.LoginResponse.member:type_name -> auth.service.v1.MemberDTO
	4, // 1: auth.service.v1.LoginResponse.token_list:type_name -> auth.service.v1.TokenDTO
	5, // 2: auth.service.v1.LoginResponse.organization_list:type_name -> auth.service.v1.OrganizationDTO
	3, // 3: auth.service.v1.TokenVerifyResponse.member:type_name -> auth.service.v1.MemberDTO
	0, // 4: auth.service.v1.AuthService.Register:input_type -> auth.service.v1.RegisterRequest
	2, // 5: auth.service.v1.AuthService.Login:input_type -> auth.service.v1.LoginRequest
	7, // 6: auth.service.v1.AuthService.TokenVerify:input_type -> auth.service.v1.TokenVerifyRequest
	1, // 7: auth.service.v1.AuthService.Register:output_type -> auth.service.v1.RegisterResponse
	6, // 8: auth.service.v1.AuthService.Login:output_type -> auth.service.v1.LoginResponse
	8, // 9: auth.service.v1.AuthService.TokenVerify:output_type -> auth.service.v1.TokenVerifyResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_service_proto_auth_auth_service_proto_init() }
func file_user_service_proto_auth_auth_service_proto_init() {
	if File_user_service_proto_auth_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_auth_auth_service_proto_rawDesc), len(file_user_service_proto_auth_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_auth_auth_service_proto_depIdxs,
		MessageInfos:      file_user_service_proto_auth_auth_service_proto_msgTypes,
	}.Build()
	File_user_service_proto_auth_auth_service_proto = out.File
	file_user_service_proto_auth_auth_service_proto_goTypes = nil
	file_user_service_proto_auth_auth_service_proto_depIdxs = nil
}
