apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: msproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: wafer233/user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: user-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: msproject
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: msproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: wafer233/project-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: project-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: msproject
spec:
  selector:
    app: project-service
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: msproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: wafer233/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: msproject
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
