// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() *App {
	config := ProvideViperConfig()
	db := ProvideDB(config)
	memberRepository := ProvideGORMMemberRepository(db)
	organizationRepository := ProvideGORMOrganizationRepository(db)
	passwordService := ProvidePasswordService()
	client := ProvideRedisClient(config)
	redisCache := ProvideRedisCache(client)
	captchaRepository := ProvideRedisCaptchaRepository(redisCache)
	tokenService := ProvideJWTTokenService(config)
	authService := ProvideDefaultAuthService(memberRepository, organizationRepository, passwordService, captchaRepository, tokenService)
	captchaService := ProvideDefaultCaptchaService(captchaRepository)
	grpcServer := ProvideGrpcServer(config, authService, captchaService)
	app := &App{
		GrpcServer: grpcServer,
	}
	return app
}
