// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() *App {
	v := ProvideMiddlewares()
	config := ProvideViperConfig()
	client := ProvideRedisClient(config)
	redisCache := ProvideRedisCache(client)
	captchaRepository := ProvideRedisCaptchaRepository(redisCache)
	captchaService := ProvideDefaultCaptchaService(captchaRepository)
	captchaHandler := ProvideCaptchaHandler(captchaService)
	db := ProvideDB(config)
	memberRepository := ProvideGORMMemberRepository(db)
	organizationRepository := ProvideGORMOrganizationRepository(db)
	passwordService := ProvidePasswordService()
	authService := ProvideDefaultAuthService(memberRepository, organizationRepository, passwordService, captchaRepository)
	loginHandler := ProvideLoginHandler(authService)
	registerHandler := ProvideRegisterHandler(authService)
	authRouter := ProvideAuthRouter(captchaHandler, loginHandler, registerHandler)
	engine := ProvideEngine(v, authRouter)
	app := &App{
		Server: engine,
	}
	return app
}
