// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() *App {
	config := ProvideViperConfig()
	client := ProvideRedisClient(config)
	captchaRepo := ProvideRedisCaptchaCache(client)
	captchaService := ProvideDefaultCaptchaService(captchaRepo)
	gormMetrics := ProvideGORMMetrics(config)
	db := ProvideDB(config, gormMetrics)
	memberRepo := ProvideGORMMemberRepository(db)
	organizationRepo := ProvideGORMOrganizationRepository(db)
	loginService := ProvideDefaultLoginService(memberRepo, organizationRepo)
	registerService := ProvideDefaultRegisterService(memberRepo, organizationRepo)
	tokenRepo := ProvideRedisTokenCache(client)
	tokenService := ProvideDefaultTokenService(config, tokenRepo)
	organizationService := ProvideDefaultOrganizationService(organizationRepo)
	loginGRPCHandler := ProvideLoginGRPCHandler(captchaService, loginService, registerService, tokenService, organizationService)
	serviceRegister := ProvideServiceRegister(loginGRPCHandler)
	userServer := ProvideUserServer(config, serviceRegister, gormMetrics)
	app := &App{
		GrpcServer: userServer,
	}
	return app
}
