// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/user/user_service.proto

package organization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberId      int64                  `protobuf:"varint,5,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Code          string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"` // 加密后的ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationDTO) Reset() {
	*x = OrganizationDTO{}
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDTO) ProtoMessage() {}

func (x *OrganizationDTO) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDTO.ProtoReflect.Descriptor instead.
func (*OrganizationDTO) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_user_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *OrganizationDTO) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationDTO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OrganizationDTO) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationDTO) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *OrganizationDTO) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrganizationDTO) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *OrganizationDTO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrganizationDTO) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *OrganizationDTO) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *OrganizationDTO) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *OrganizationDTO) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type OrgListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      int64                  `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgListRequest) Reset() {
	*x = OrgListRequest{}
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgListRequest) ProtoMessage() {}

func (x *OrgListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgListRequest.ProtoReflect.Descriptor instead.
func (*OrgListRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_user_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *OrgListRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type OrgListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationList []*OrganizationDTO     `protobuf:"bytes,1,rep,name=organization_list,json=organizationList,proto3" json:"organization_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrgListResponse) Reset() {
	*x = OrgListResponse{}
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgListResponse) ProtoMessage() {}

func (x *OrgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_user_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgListResponse.ProtoReflect.Descriptor instead.
func (*OrgListResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_user_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *OrgListResponse) GetOrganizationList() []*OrganizationDTO {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

var File_api_gateway_proto_user_user_service_proto protoreflect.FileDescriptor

const file_api_gateway_proto_user_user_service_proto_rawDesc = "" +
	"\n" +
	")api-gateway/proto/user/user_service.proto\x12\x17organization.service.v1\"\xbb\x02\n" +
	"\x0fOrganizationDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tmember_id\x18\x05 \x01(\x03R\bmemberId\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\"-\n" +
	"\x0eOrgListRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x03R\bmemberId\"h\n" +
	"\x0fOrgListResponse\x12U\n" +
	"\x11organization_list\x18\x01 \x03(\v2(.organization.service.v1.OrganizationDTOR\x10organizationList2x\n" +
	"\x13OrganizationService\x12a\n" +
	"\n" +
	"GetOrgList\x12'.organization.service.v1.OrgListRequest\x1a(.organization.service.v1.OrgListResponse\"\x00BBZ@github.com/Wafer233/msproject-be/user-service/proto/organizationb\x06proto3"

var (
	file_api_gateway_proto_user_user_service_proto_rawDescOnce sync.Once
	file_api_gateway_proto_user_user_service_proto_rawDescData []byte
)

func file_api_gateway_proto_user_user_service_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_user_user_service_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_user_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_user_user_service_proto_rawDesc), len(file_api_gateway_proto_user_user_service_proto_rawDesc)))
	})
	return file_api_gateway_proto_user_user_service_proto_rawDescData
}

var file_api_gateway_proto_user_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_proto_user_user_service_proto_goTypes = []any{
	(*OrganizationDTO)(nil), // 0: organization.service.v1.OrganizationDTO
	(*OrgListRequest)(nil),  // 1: organization.service.v1.OrgListRequest
	(*OrgListResponse)(nil), // 2: organization.service.v1.OrgListResponse
}
var file_api_gateway_proto_user_user_service_proto_depIdxs = []int32{
	0, // 0: organization.service.v1.OrgListResponse.organization_list:type_name -> organization.service.v1.OrganizationDTO
	1, // 1: organization.service.v1.OrganizationService.GetOrgList:input_type -> organization.service.v1.OrgListRequest
	2, // 2: organization.service.v1.OrganizationService.GetOrgList:output_type -> organization.service.v1.OrgListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_user_user_service_proto_init() }
func file_api_gateway_proto_user_user_service_proto_init() {
	if File_api_gateway_proto_user_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_user_user_service_proto_rawDesc), len(file_api_gateway_proto_user_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_user_user_service_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_user_user_service_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_user_user_service_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_user_user_service_proto = out.File
	file_api_gateway_proto_user_user_service_proto_goTypes = nil
	file_api_gateway_proto_user_user_service_proto_depIdxs = nil
}
