// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/captcha/captcha_service.proto

package captcha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_proto_captcha_captcha_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_captcha_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_proto_captcha_captcha_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCaptchaRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type GetCaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaResponse) Reset() {
	*x = GetCaptchaResponse{}
	mi := &file_proto_captcha_captcha_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaResponse) ProtoMessage() {}

func (x *GetCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_captcha_captcha_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaResponse.ProtoReflect.Descriptor instead.
func (*GetCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_proto_captcha_captcha_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaptchaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCaptchaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCaptchaResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_proto_captcha_captcha_service_proto protoreflect.FileDescriptor

const file_proto_captcha_captcha_service_proto_rawDesc = "" +
	"\n" +
	"#proto/captcha/captcha_service.proto\x12\x12captcha.service.v1\"+\n" +
	"\x11GetCaptchaRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"\\\n" +
	"\x12GetCaptchaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code2o\n" +
	"\x0eCaptchaService\x12]\n" +
	"\n" +
	"GetCaptcha\x12%.captcha.service.v1.GetCaptchaRequest\x1a&.captcha.service.v1.GetCaptchaResponse\"\x00B=Z;github.com/Wafer233/msproject-be/user-service/proto/captchab\x06proto3"

var (
	file_proto_captcha_captcha_service_proto_rawDescOnce sync.Once
	file_proto_captcha_captcha_service_proto_rawDescData []byte
)

func file_proto_captcha_captcha_service_proto_rawDescGZIP() []byte {
	file_proto_captcha_captcha_service_proto_rawDescOnce.Do(func() {
		file_proto_captcha_captcha_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_captcha_captcha_service_proto_rawDesc), len(file_proto_captcha_captcha_service_proto_rawDesc)))
	})
	return file_proto_captcha_captcha_service_proto_rawDescData
}

var file_proto_captcha_captcha_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_captcha_captcha_service_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),  // 0: captcha.service.v1.GetCaptchaRequest
	(*GetCaptchaResponse)(nil), // 1: captcha.service.v1.GetCaptchaResponse
}
var file_proto_captcha_captcha_service_proto_depIdxs = []int32{
	0, // 0: captcha.service.v1.CaptchaService.GetCaptcha:input_type -> captcha.service.v1.GetCaptchaRequest
	1, // 1: captcha.service.v1.CaptchaService.GetCaptcha:output_type -> captcha.service.v1.GetCaptchaResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_captcha_captcha_service_proto_init() }
func file_proto_captcha_captcha_service_proto_init() {
	if File_proto_captcha_captcha_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_captcha_captcha_service_proto_rawDesc), len(file_proto_captcha_captcha_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_captcha_captcha_service_proto_goTypes,
		DependencyIndexes: file_proto_captcha_captcha_service_proto_depIdxs,
		MessageInfos:      file_proto_captcha_captcha_service_proto_msgTypes,
	}.Build()
	File_proto_captcha_captcha_service_proto = out.File
	file_proto_captcha_captcha_service_proto_goTypes = nil
	file_proto_captcha_captcha_service_proto_depIdxs = nil
}
