// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/index/index.proto

package index

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMessage) Reset() {
	*x = IndexMessage{}
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMessage) ProtoMessage() {}

func (x *IndexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMessage.ProtoReflect.Descriptor instead.
func (*IndexMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_index_index_proto_rawDescGZIP(), []int{0}
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menus         []*Menu                `protobuf:"bytes,1,rep,name=menus,proto3" json:"menus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_index_index_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetMenus() []*Menu {
	if x != nil {
		return x.Menus
	}
	return nil
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Node          string                 `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      int64                  `protobuf:"varint,11,opt,name=createBy,proto3" json:"createBy,omitempty"`
	IsInner       int32                  `protobuf:"varint,12,opt,name=isInner,proto3" json:"isInner,omitempty"`
	Values        string                 `protobuf:"bytes,13,opt,name=values,proto3" json:"values,omitempty"`
	ShowSlider    int32                  `protobuf:"varint,14,opt,name=showSlider,proto3" json:"showSlider,omitempty"`
	StatusText    string                 `protobuf:"bytes,15,opt,name=statusText,proto3" json:"statusText,omitempty"`
	InnerText     string                 `protobuf:"bytes,16,opt,name=innerText,proto3" json:"innerText,omitempty"`
	FullUrl       string                 `protobuf:"bytes,17,opt,name=fullUrl,proto3" json:"fullUrl,omitempty"`
	Children      []*Menu                `protobuf:"bytes,18,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_index_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_index_index_proto_rawDescGZIP(), []int{2}
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Menu) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Menu) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Menu) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Menu) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Menu) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Menu) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Menu) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Menu) GetIsInner() int32 {
	if x != nil {
		return x.IsInner
	}
	return 0
}

func (x *Menu) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

func (x *Menu) GetShowSlider() int32 {
	if x != nil {
		return x.ShowSlider
	}
	return 0
}

func (x *Menu) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *Menu) GetInnerText() string {
	if x != nil {
		return x.InnerText
	}
	return ""
}

func (x *Menu) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *Menu) GetChildren() []*Menu {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_api_gateway_proto_index_index_proto protoreflect.FileDescriptor

const file_api_gateway_proto_index_index_proto_rawDesc = "" +
	"\n" +
	"#api-gateway/proto/index/index.proto\x12\x10index.service.v1\"\x0e\n" +
	"\fIndexMessage\"=\n" +
	"\rIndexResponse\x12,\n" +
	"\x05menus\x18\x01 \x03(\v2\x16.index.service.v1.MenuR\x05menus\"\xd2\x03\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilePath\x18\x06 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x12\n" +
	"\x04node\x18\b \x01(\tR\x04node\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\v \x01(\x03R\bcreateBy\x12\x18\n" +
	"\aisInner\x18\f \x01(\x05R\aisInner\x12\x16\n" +
	"\x06values\x18\r \x01(\tR\x06values\x12\x1e\n" +
	"\n" +
	"showSlider\x18\x0e \x01(\x05R\n" +
	"showSlider\x12\x1e\n" +
	"\n" +
	"statusText\x18\x0f \x01(\tR\n" +
	"statusText\x12\x1c\n" +
	"\tinnerText\x18\x10 \x01(\tR\tinnerText\x12\x18\n" +
	"\afullUrl\x18\x11 \x01(\tR\afullUrl\x122\n" +
	"\bchildren\x18\x12 \x03(\v2\x16.index.service.v1.MenuR\bchildren2Z\n" +
	"\fIndexService\x12J\n" +
	"\x05Index\x12\x1e.index.service.v1.IndexMessage\x1a\x1f.index.service.v1.IndexResponse\"\x00B:Z8github.com/Wafer233/msproject-be/api-gateway/proto/indexb\x06proto3"

var (
	file_api_gateway_proto_index_index_proto_rawDescOnce sync.Once
	file_api_gateway_proto_index_index_proto_rawDescData []byte
)

func file_api_gateway_proto_index_index_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_index_index_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_index_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_index_index_proto_rawDesc), len(file_api_gateway_proto_index_index_proto_rawDesc)))
	})
	return file_api_gateway_proto_index_index_proto_rawDescData
}

var file_api_gateway_proto_index_index_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_proto_index_index_proto_goTypes = []any{
	(*IndexMessage)(nil),  // 0: index.service.v1.IndexMessage
	(*IndexResponse)(nil), // 1: index.service.v1.IndexResponse
	(*Menu)(nil),          // 2: index.service.v1.Menu
}
var file_api_gateway_proto_index_index_proto_depIdxs = []int32{
	2, // 0: index.service.v1.IndexResponse.menus:type_name -> index.service.v1.Menu
	2, // 1: index.service.v1.Menu.children:type_name -> index.service.v1.Menu
	0, // 2: index.service.v1.IndexService.Index:input_type -> index.service.v1.IndexMessage
	1, // 3: index.service.v1.IndexService.Index:output_type -> index.service.v1.IndexResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_index_index_proto_init() }
func file_api_gateway_proto_index_index_proto_init() {
	if File_api_gateway_proto_index_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_index_index_proto_rawDesc), len(file_api_gateway_proto_index_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_index_index_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_index_index_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_index_index_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_index_index_proto = out.File
	file_api_gateway_proto_index_index_proto_goTypes = nil
	file_api_gateway_proto_index_index_proto_depIdxs = nil
}
