// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() (*App, error) {
	v := ProvideMiddlewares()
	config := ProvideViperConfig()
	grpcClientManager, err := ProvideGrpcClientManager(config)
	if err != nil {
		return nil, err
	}
	captchaService := ProvideCaptchaService(grpcClientManager)
	metricsCollector := ProvideMetricsCollector(config)
	captchaHandler := ProvideCaptchaHandler(captchaService, metricsCollector)
	authService := ProvideAuthService(grpcClientManager)
	loginHandler := ProvideLoginHandler(authService, metricsCollector)
	registerHandler := ProvideRegisterHandler(authService, metricsCollector)
	authRouter := ProvideAuthRouter(captchaHandler, loginHandler, registerHandler)
	menuService := ProvideMenuService(grpcClientManager)
	menuHandler := ProvideMenuHandler(menuService, metricsCollector)
	menuRouter := ProvideMenuRouter(menuHandler)
	v2 := ProvideRouters(authRouter, menuRouter)
	engine := ProvideGinEngine(v, v2)
	app := &App{
		Server: engine,
	}
	return app, nil
}
