// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

// Injectors from wire.go:

func InitApp() (*App, error) {
	config := ProvideViperConfig()
	metricsCollector := ProvideMetricsCollector(config)
	v := ProvideMiddlewares(config, metricsCollector)
	grpcClientManager, err := ProvideGrpcClientManager(config)
	if err != nil {
		return nil, err
	}
	captchaService := ProvideCaptchaService(grpcClientManager)
	captchaHandler := ProvideCaptchaHandler(captchaService)
	authService := ProvideAuthService(grpcClientManager)
	loginHandler := ProvideLoginHandler(authService)
	registerHandler := ProvideRegisterHandler(authService)
	authRouter := ProvideAuthRouter(captchaHandler, loginHandler, registerHandler)
	menuService := ProvideMenuService(grpcClientManager)
	menuHandler := ProvideMenuHandler(menuService)
	handlerFunc := ProvideAuthMiddleware(grpcClientManager)
	menuRouter := ProvideMenuRouter(menuHandler, handlerFunc)
	projectService := ProvideProjectService(grpcClientManager)
	projectHandler := ProvideProjectHandler(projectService)
	projectRouter := ProvideProjectRouter(projectHandler, handlerFunc)
	v2 := ProvideRouters(authRouter, menuRouter, projectRouter)
	engine := ProvideGinEngine(config, v, v2, metricsCollector)
	app := &App{
		Server: engine,
	}
	return app, nil
}
