scrape_configs:
  - job_name: "api-gateway"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: [ "host.docker.internal:80" ]
    metrics_path: "/metrics"

  - job_name: "user-service"
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: [ "host.docker.internal:8090" ]
    metrics_path: "/metrics"
