// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelfListMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	MemberName       string                 `protobuf:"bytes,2,opt,name=memberName,proto3" json:"memberName,omitempty"`
	Page             int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SelectBy         string                 `protobuf:"bytes,5,opt,name=selectBy,proto3" json:"selectBy,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,6,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	ViewType         int32                  `protobuf:"varint,7,opt,name=viewType,proto3" json:"viewType,omitempty"`
	Name             string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	TemplateCode     string                 `protobuf:"bytes,9,opt,name=templateCode,proto3" json:"templateCode,omitempty"`
	Description      string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Id               int64                  `protobuf:"varint,11,opt,name=id,proto3" json:"id,omitempty"`
	ProjectCode      string                 `protobuf:"bytes,12,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	Deleted          bool                   `protobuf:"varint,13,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CollectType      string                 `protobuf:"bytes,14,opt,name=collectType,proto3" json:"collectType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SelfListMessage) Reset() {
	*x = SelfListMessage{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfListMessage) ProtoMessage() {}

func (x *SelfListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfListMessage.ProtoReflect.Descriptor instead.
func (*SelfListMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *SelfListMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *SelfListMessage) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *SelfListMessage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SelfListMessage) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SelfListMessage) GetSelectBy() string {
	if x != nil {
		return x.SelectBy
	}
	return ""
}

func (x *SelfListMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *SelfListMessage) GetViewType() int32 {
	if x != nil {
		return x.ViewType
	}
	return 0
}

func (x *SelfListMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelfListMessage) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SelfListMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SelfListMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelfListMessage) GetProjectCode() string {
	if x != nil {
		return x.ProjectCode
	}
	return ""
}

func (x *SelfListMessage) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SelfListMessage) GetCollectType() string {
	if x != nil {
		return x.CollectType
	}
	return ""
}

type SelfListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Project             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfListResponse) Reset() {
	*x = SelfListResponse{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfListResponse) ProtoMessage() {}

func (x *SelfListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfListResponse.ProtoReflect.Descriptor instead.
func (*SelfListResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *SelfListResponse) GetList() []*Project {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SelfListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Project struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Cover              string                 `protobuf:"bytes,2,opt,name=Cover,proto3" json:"Cover,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	AccessControlType  string                 `protobuf:"bytes,5,opt,name=AccessControlType,proto3" json:"AccessControlType,omitempty"`
	WhiteList          string                 `protobuf:"bytes,6,opt,name=WhiteList,proto3" json:"WhiteList,omitempty"`
	Order              int32                  `protobuf:"varint,7,opt,name=Order,proto3" json:"Order,omitempty"`
	Deleted            int32                  `protobuf:"varint,8,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	TemplateCode       string                 `protobuf:"bytes,9,opt,name=TemplateCode,proto3" json:"TemplateCode,omitempty"`
	Schedule           float64                `protobuf:"fixed64,10,opt,name=Schedule,proto3" json:"Schedule,omitempty"`
	CreateTime         string                 `protobuf:"bytes,11,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	OrganizationCode   string                 `protobuf:"bytes,12,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	DeletedTime        string                 `protobuf:"bytes,13,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"`
	Private            int32                  `protobuf:"varint,14,opt,name=Private,proto3" json:"Private,omitempty"`
	Prefix             string                 `protobuf:"bytes,15,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	OpenPrefix         int32                  `protobuf:"varint,16,opt,name=OpenPrefix,proto3" json:"OpenPrefix,omitempty"`
	Archive            int32                  `protobuf:"varint,17,opt,name=Archive,proto3" json:"Archive,omitempty"`
	ArchiveTime        int64                  `protobuf:"varint,18,opt,name=ArchiveTime,proto3" json:"ArchiveTime,omitempty"`
	OpenBeginTime      int32                  `protobuf:"varint,19,opt,name=OpenBeginTime,proto3" json:"OpenBeginTime,omitempty"`
	OpenTaskPrivate    int32                  `protobuf:"varint,20,opt,name=OpenTaskPrivate,proto3" json:"OpenTaskPrivate,omitempty"`
	TaskBoardTheme     string                 `protobuf:"bytes,21,opt,name=TaskBoardTheme,proto3" json:"TaskBoardTheme,omitempty"`
	BeginTime          string                 `protobuf:"bytes,22,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`
	EndTime            string                 `protobuf:"bytes,23,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	AutoUpdateSchedule int32                  `protobuf:"varint,24,opt,name=AutoUpdateSchedule,proto3" json:"AutoUpdateSchedule,omitempty"`
	ProjectCode        int64                  `protobuf:"varint,25,opt,name=ProjectCode,proto3" json:"ProjectCode,omitempty"`
	MemberCode         int64                  `protobuf:"varint,26,opt,name=MemberCode,proto3" json:"MemberCode,omitempty"`
	JoinTime           string                 `protobuf:"bytes,27,opt,name=JoinTime,proto3" json:"JoinTime,omitempty"`
	IsOwner            int64                  `protobuf:"varint,28,opt,name=IsOwner,proto3" json:"IsOwner,omitempty"`
	Authorize          string                 `protobuf:"bytes,29,opt,name=Authorize,proto3" json:"Authorize,omitempty"`
	Code               string                 `protobuf:"bytes,30,opt,name=code,proto3" json:"code,omitempty"`
	OwnerName          string                 `protobuf:"bytes,31,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	Collected          int32                  `protobuf:"varint,32,opt,name=collected,proto3" json:"collected,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetAccessControlType() string {
	if x != nil {
		return x.AccessControlType
	}
	return ""
}

func (x *Project) GetWhiteList() string {
	if x != nil {
		return x.WhiteList
	}
	return ""
}

func (x *Project) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Project) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *Project) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *Project) GetSchedule() float64 {
	if x != nil {
		return x.Schedule
	}
	return 0
}

func (x *Project) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Project) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *Project) GetDeletedTime() string {
	if x != nil {
		return x.DeletedTime
	}
	return ""
}

func (x *Project) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *Project) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Project) GetOpenPrefix() int32 {
	if x != nil {
		return x.OpenPrefix
	}
	return 0
}

func (x *Project) GetArchive() int32 {
	if x != nil {
		return x.Archive
	}
	return 0
}

func (x *Project) GetArchiveTime() int64 {
	if x != nil {
		return x.ArchiveTime
	}
	return 0
}

func (x *Project) GetOpenBeginTime() int32 {
	if x != nil {
		return x.OpenBeginTime
	}
	return 0
}

func (x *Project) GetOpenTaskPrivate() int32 {
	if x != nil {
		return x.OpenTaskPrivate
	}
	return 0
}

func (x *Project) GetTaskBoardTheme() string {
	if x != nil {
		return x.TaskBoardTheme
	}
	return ""
}

func (x *Project) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *Project) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Project) GetAutoUpdateSchedule() int32 {
	if x != nil {
		return x.AutoUpdateSchedule
	}
	return 0
}

func (x *Project) GetProjectCode() int64 {
	if x != nil {
		return x.ProjectCode
	}
	return 0
}

func (x *Project) GetMemberCode() int64 {
	if x != nil {
		return x.MemberCode
	}
	return 0
}

func (x *Project) GetJoinTime() string {
	if x != nil {
		return x.JoinTime
	}
	return ""
}

func (x *Project) GetIsOwner() int64 {
	if x != nil {
		return x.IsOwner
	}
	return 0
}

func (x *Project) GetAuthorize() string {
	if x != nil {
		return x.Authorize
	}
	return ""
}

func (x *Project) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Project) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Project) GetCollected() int32 {
	if x != nil {
		return x.Collected
	}
	return 0
}

var File_api_gateway_proto_project_project_proto protoreflect.FileDescriptor

const file_api_gateway_proto_project_project_proto_rawDesc = "" +
	"\n" +
	"'api-gateway/proto/project/project.proto\x12\x12project.service.v1\"\xa9\x03\n" +
	"\x0fSelfListMessage\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12\x1e\n" +
	"\n" +
	"memberName\x18\x02 \x01(\tR\n" +
	"memberName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bselectBy\x18\x05 \x01(\tR\bselectBy\x12*\n" +
	"\x10organizationCode\x18\x06 \x01(\tR\x10organizationCode\x12\x1a\n" +
	"\bviewType\x18\a \x01(\x05R\bviewType\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\"\n" +
	"\ftemplateCode\x18\t \x01(\tR\ftemplateCode\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\v \x01(\x03R\x02id\x12 \n" +
	"\vprojectCode\x18\f \x01(\tR\vprojectCode\x12\x18\n" +
	"\adeleted\x18\r \x01(\bR\adeleted\x12 \n" +
	"\vcollectType\x18\x0e \x01(\tR\vcollectType\"Y\n" +
	"\x10SelfListResponse\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.project.service.v1.ProjectR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xe3\a\n" +
	"\aProject\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Cover\x18\x02 \x01(\tR\x05Cover\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12,\n" +
	"\x11AccessControlType\x18\x05 \x01(\tR\x11AccessControlType\x12\x1c\n" +
	"\tWhiteList\x18\x06 \x01(\tR\tWhiteList\x12\x14\n" +
	"\x05Order\x18\a \x01(\x05R\x05Order\x12\x18\n" +
	"\aDeleted\x18\b \x01(\x05R\aDeleted\x12\"\n" +
	"\fTemplateCode\x18\t \x01(\tR\fTemplateCode\x12\x1a\n" +
	"\bSchedule\x18\n" +
	" \x01(\x01R\bSchedule\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\v \x01(\tR\n" +
	"CreateTime\x12*\n" +
	"\x10OrganizationCode\x18\f \x01(\tR\x10OrganizationCode\x12 \n" +
	"\vDeletedTime\x18\r \x01(\tR\vDeletedTime\x12\x18\n" +
	"\aPrivate\x18\x0e \x01(\x05R\aPrivate\x12\x16\n" +
	"\x06Prefix\x18\x0f \x01(\tR\x06Prefix\x12\x1e\n" +
	"\n" +
	"OpenPrefix\x18\x10 \x01(\x05R\n" +
	"OpenPrefix\x12\x18\n" +
	"\aArchive\x18\x11 \x01(\x05R\aArchive\x12 \n" +
	"\vArchiveTime\x18\x12 \x01(\x03R\vArchiveTime\x12$\n" +
	"\rOpenBeginTime\x18\x13 \x01(\x05R\rOpenBeginTime\x12(\n" +
	"\x0fOpenTaskPrivate\x18\x14 \x01(\x05R\x0fOpenTaskPrivate\x12&\n" +
	"\x0eTaskBoardTheme\x18\x15 \x01(\tR\x0eTaskBoardTheme\x12\x1c\n" +
	"\tBeginTime\x18\x16 \x01(\tR\tBeginTime\x12\x18\n" +
	"\aEndTime\x18\x17 \x01(\tR\aEndTime\x12.\n" +
	"\x12AutoUpdateSchedule\x18\x18 \x01(\x05R\x12AutoUpdateSchedule\x12 \n" +
	"\vProjectCode\x18\x19 \x01(\x03R\vProjectCode\x12\x1e\n" +
	"\n" +
	"MemberCode\x18\x1a \x01(\x03R\n" +
	"MemberCode\x12\x1a\n" +
	"\bJoinTime\x18\x1b \x01(\tR\bJoinTime\x12\x18\n" +
	"\aIsOwner\x18\x1c \x01(\x03R\aIsOwner\x12\x1c\n" +
	"\tAuthorize\x18\x1d \x01(\tR\tAuthorize\x12\x12\n" +
	"\x04code\x18\x1e \x01(\tR\x04code\x12\x1c\n" +
	"\townerName\x18\x1f \x01(\tR\townerName\x12\x1c\n" +
	"\tcollected\x18  \x01(\x05R\tcollected2i\n" +
	"\x0eProjectService\x12W\n" +
	"\bSelfList\x12#.project.service.v1.SelfListMessage\x1a$.project.service.v1.SelfListResponse\"\x00B<Z:github.com/Wafer233/msproject-be/api-gateway/proto/projectb\x06proto3"

var (
	file_api_gateway_proto_project_project_proto_rawDescOnce sync.Once
	file_api_gateway_proto_project_project_proto_rawDescData []byte
)

func file_api_gateway_proto_project_project_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_project_project_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_project_project_proto_rawDesc), len(file_api_gateway_proto_project_project_proto_rawDesc)))
	})
	return file_api_gateway_proto_project_project_proto_rawDescData
}

var file_api_gateway_proto_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_proto_project_project_proto_goTypes = []any{
	(*SelfListMessage)(nil),  // 0: project.service.v1.SelfListMessage
	(*SelfListResponse)(nil), // 1: project.service.v1.SelfListResponse
	(*Project)(nil),          // 2: project.service.v1.Project
}
var file_api_gateway_proto_project_project_proto_depIdxs = []int32{
	2, // 0: project.service.v1.SelfListResponse.list:type_name -> project.service.v1.Project
	0, // 1: project.service.v1.ProjectService.SelfList:input_type -> project.service.v1.SelfListMessage
	1, // 2: project.service.v1.ProjectService.SelfList:output_type -> project.service.v1.SelfListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_project_project_proto_init() }
func file_api_gateway_proto_project_project_proto_init() {
	if File_api_gateway_proto_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_project_project_proto_rawDesc), len(file_api_gateway_proto_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_project_project_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_project_project_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_project_project_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_project_project_proto = out.File
	file_api_gateway_proto_project_project_proto_goTypes = nil
	file_api_gateway_proto_project_project_proto_depIdxs = nil
}
