// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------- Index -----------------
type IndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexRequest) Reset() {
	*x = IndexRequest{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexRequest) ProtoMessage() {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexRequest.ProtoReflect.Descriptor instead.
func (*IndexRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{0}
}

type IndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuList      []*Menu                `protobuf:"bytes,1,rep,name=menuList,proto3" json:"menuList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexResponse) Reset() {
	*x = IndexResponse{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexResponse) ProtoMessage() {}

func (x *IndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexResponse.ProtoReflect.Descriptor instead.
func (*IndexResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{1}
}

func (x *IndexResponse) GetMenuList() []*Menu {
	if x != nil {
		return x.MenuList
	}
	return nil
}

// ----------------SelfProject -----------------
type SelfProjectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MemberId         int64                  `protobuf:"varint,1,opt,name=memberId,proto3" json:"memberId,omitempty"`
	MemberName       string                 `protobuf:"bytes,2,opt,name=memberName,proto3" json:"memberName,omitempty"`
	Page             int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SelectBy         string                 `protobuf:"bytes,5,opt,name=selectBy,proto3" json:"selectBy,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,6,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	ViewType         int32                  `protobuf:"varint,7,opt,name=viewType,proto3" json:"viewType,omitempty"`
	Name             string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	TemplateCode     string                 `protobuf:"bytes,9,opt,name=templateCode,proto3" json:"templateCode,omitempty"`
	Description      string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Id               int64                  `protobuf:"varint,11,opt,name=id,proto3" json:"id,omitempty"`
	ProjectCode      string                 `protobuf:"bytes,12,opt,name=projectCode,proto3" json:"projectCode,omitempty"`
	Deleted          bool                   `protobuf:"varint,13,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CollectType      string                 `protobuf:"bytes,14,opt,name=collectType,proto3" json:"collectType,omitempty"`
	TaskCode         string                 `protobuf:"bytes,15,opt,name=taskCode,proto3" json:"taskCode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SelfProjectRequest) Reset() {
	*x = SelfProjectRequest{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfProjectRequest) ProtoMessage() {}

func (x *SelfProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfProjectRequest.ProtoReflect.Descriptor instead.
func (*SelfProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *SelfProjectRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *SelfProjectRequest) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *SelfProjectRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SelfProjectRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SelfProjectRequest) GetSelectBy() string {
	if x != nil {
		return x.SelectBy
	}
	return ""
}

func (x *SelfProjectRequest) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *SelfProjectRequest) GetViewType() int32 {
	if x != nil {
		return x.ViewType
	}
	return 0
}

func (x *SelfProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SelfProjectRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SelfProjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SelfProjectRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SelfProjectRequest) GetProjectCode() string {
	if x != nil {
		return x.ProjectCode
	}
	return ""
}

func (x *SelfProjectRequest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *SelfProjectRequest) GetCollectType() string {
	if x != nil {
		return x.CollectType
	}
	return ""
}

func (x *SelfProjectRequest) GetTaskCode() string {
	if x != nil {
		return x.TaskCode
	}
	return ""
}

type SelfProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfProjectResponse) Reset() {
	*x = SelfProjectResponse{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfProjectResponse) ProtoMessage() {}

func (x *SelfProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfProjectResponse.ProtoReflect.Descriptor instead.
func (*SelfProjectResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *SelfProjectResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *SelfProjectResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ------------------common -----------------
type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           int64                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	FilePath      string                 `protobuf:"bytes,6,opt,name=filePath,proto3" json:"filePath,omitempty"`
	Params        string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`
	Node          string                 `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	CreateBy      int64                  `protobuf:"varint,11,opt,name=createBy,proto3" json:"createBy,omitempty"`
	IsInner       int32                  `protobuf:"varint,12,opt,name=isInner,proto3" json:"isInner,omitempty"`
	Values        string                 `protobuf:"bytes,13,opt,name=values,proto3" json:"values,omitempty"`
	ShowSlider    int32                  `protobuf:"varint,14,opt,name=showSlider,proto3" json:"showSlider,omitempty"`
	StatusText    string                 `protobuf:"bytes,15,opt,name=statusText,proto3" json:"statusText,omitempty"`
	InnerText     string                 `protobuf:"bytes,16,opt,name=innerText,proto3" json:"innerText,omitempty"`
	FullUrl       string                 `protobuf:"bytes,17,opt,name=fullUrl,proto3" json:"fullUrl,omitempty"`
	MenuList      []*Menu                `protobuf:"bytes,18,rep,name=menuList,proto3" json:"menuList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *Menu) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Menu) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Menu) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Menu) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Menu) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Menu) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Menu) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Menu) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Menu) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Menu) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Menu) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *Menu) GetIsInner() int32 {
	if x != nil {
		return x.IsInner
	}
	return 0
}

func (x *Menu) GetValues() string {
	if x != nil {
		return x.Values
	}
	return ""
}

func (x *Menu) GetShowSlider() int32 {
	if x != nil {
		return x.ShowSlider
	}
	return 0
}

func (x *Menu) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *Menu) GetInnerText() string {
	if x != nil {
		return x.InnerText
	}
	return ""
}

func (x *Menu) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *Menu) GetMenuList() []*Menu {
	if x != nil {
		return x.MenuList
	}
	return nil
}

type Project struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Cover              string                 `protobuf:"bytes,2,opt,name=Cover,proto3" json:"Cover,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	AccessControlType  string                 `protobuf:"bytes,5,opt,name=AccessControlType,proto3" json:"AccessControlType,omitempty"`
	WhiteList          string                 `protobuf:"bytes,6,opt,name=WhiteList,proto3" json:"WhiteList,omitempty"`
	Order              int32                  `protobuf:"varint,7,opt,name=Order,proto3" json:"Order,omitempty"`
	Deleted            int32                  `protobuf:"varint,8,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	TemplateCode       string                 `protobuf:"bytes,9,opt,name=TemplateCode,proto3" json:"TemplateCode,omitempty"`
	Schedule           float64                `protobuf:"fixed64,10,opt,name=Schedule,proto3" json:"Schedule,omitempty"`
	CreateTime         string                 `protobuf:"bytes,11,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	OrganizationCode   string                 `protobuf:"bytes,12,opt,name=OrganizationCode,proto3" json:"OrganizationCode,omitempty"`
	DeletedTime        string                 `protobuf:"bytes,13,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"`
	Private            int32                  `protobuf:"varint,14,opt,name=Private,proto3" json:"Private,omitempty"`
	Prefix             string                 `protobuf:"bytes,15,opt,name=Prefix,proto3" json:"Prefix,omitempty"`
	OpenPrefix         int32                  `protobuf:"varint,16,opt,name=OpenPrefix,proto3" json:"OpenPrefix,omitempty"`
	Archive            int32                  `protobuf:"varint,17,opt,name=Archive,proto3" json:"Archive,omitempty"`
	ArchiveTime        int64                  `protobuf:"varint,18,opt,name=ArchiveTime,proto3" json:"ArchiveTime,omitempty"`
	OpenBeginTime      int32                  `protobuf:"varint,19,opt,name=OpenBeginTime,proto3" json:"OpenBeginTime,omitempty"`
	OpenTaskPrivate    int32                  `protobuf:"varint,20,opt,name=OpenTaskPrivate,proto3" json:"OpenTaskPrivate,omitempty"`
	TaskBoardTheme     string                 `protobuf:"bytes,21,opt,name=TaskBoardTheme,proto3" json:"TaskBoardTheme,omitempty"`
	BeginTime          string                 `protobuf:"bytes,22,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`
	EndTime            string                 `protobuf:"bytes,23,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	AutoUpdateSchedule int32                  `protobuf:"varint,24,opt,name=AutoUpdateSchedule,proto3" json:"AutoUpdateSchedule,omitempty"`
	ProjectCode        int64                  `protobuf:"varint,25,opt,name=ProjectCode,proto3" json:"ProjectCode,omitempty"`
	MemberCode         int64                  `protobuf:"varint,26,opt,name=MemberCode,proto3" json:"MemberCode,omitempty"`
	JoinTime           string                 `protobuf:"bytes,27,opt,name=JoinTime,proto3" json:"JoinTime,omitempty"`
	IsOwner            int64                  `protobuf:"varint,28,opt,name=IsOwner,proto3" json:"IsOwner,omitempty"`
	Authorize          string                 `protobuf:"bytes,29,opt,name=Authorize,proto3" json:"Authorize,omitempty"`
	Code               string                 `protobuf:"bytes,30,opt,name=code,proto3" json:"code,omitempty"`
	OwnerName          string                 `protobuf:"bytes,31,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	Collected          int32                  `protobuf:"varint,32,opt,name=collected,proto3" json:"collected,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_project_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_project_project_proto_rawDescGZIP(), []int{5}
}

func (x *Project) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Project) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetAccessControlType() string {
	if x != nil {
		return x.AccessControlType
	}
	return ""
}

func (x *Project) GetWhiteList() string {
	if x != nil {
		return x.WhiteList
	}
	return ""
}

func (x *Project) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Project) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *Project) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *Project) GetSchedule() float64 {
	if x != nil {
		return x.Schedule
	}
	return 0
}

func (x *Project) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Project) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

func (x *Project) GetDeletedTime() string {
	if x != nil {
		return x.DeletedTime
	}
	return ""
}

func (x *Project) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *Project) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Project) GetOpenPrefix() int32 {
	if x != nil {
		return x.OpenPrefix
	}
	return 0
}

func (x *Project) GetArchive() int32 {
	if x != nil {
		return x.Archive
	}
	return 0
}

func (x *Project) GetArchiveTime() int64 {
	if x != nil {
		return x.ArchiveTime
	}
	return 0
}

func (x *Project) GetOpenBeginTime() int32 {
	if x != nil {
		return x.OpenBeginTime
	}
	return 0
}

func (x *Project) GetOpenTaskPrivate() int32 {
	if x != nil {
		return x.OpenTaskPrivate
	}
	return 0
}

func (x *Project) GetTaskBoardTheme() string {
	if x != nil {
		return x.TaskBoardTheme
	}
	return ""
}

func (x *Project) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *Project) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Project) GetAutoUpdateSchedule() int32 {
	if x != nil {
		return x.AutoUpdateSchedule
	}
	return 0
}

func (x *Project) GetProjectCode() int64 {
	if x != nil {
		return x.ProjectCode
	}
	return 0
}

func (x *Project) GetMemberCode() int64 {
	if x != nil {
		return x.MemberCode
	}
	return 0
}

func (x *Project) GetJoinTime() string {
	if x != nil {
		return x.JoinTime
	}
	return ""
}

func (x *Project) GetIsOwner() int64 {
	if x != nil {
		return x.IsOwner
	}
	return 0
}

func (x *Project) GetAuthorize() string {
	if x != nil {
		return x.Authorize
	}
	return ""
}

func (x *Project) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Project) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Project) GetCollected() int32 {
	if x != nil {
		return x.Collected
	}
	return 0
}

var File_api_gateway_proto_project_project_proto protoreflect.FileDescriptor

const file_api_gateway_proto_project_project_proto_rawDesc = "" +
	"\n" +
	"'api-gateway/proto/project/project.proto\x12\n" +
	"project.v1\"\x0e\n" +
	"\fIndexRequest\"=\n" +
	"\rIndexResponse\x12,\n" +
	"\bmenuList\x18\x01 \x03(\v2\x10.project.v1.MenuR\bmenuList\"\xc8\x03\n" +
	"\x12SelfProjectRequest\x12\x1a\n" +
	"\bmemberId\x18\x01 \x01(\x03R\bmemberId\x12\x1e\n" +
	"\n" +
	"memberName\x18\x02 \x01(\tR\n" +
	"memberName\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bselectBy\x18\x05 \x01(\tR\bselectBy\x12*\n" +
	"\x10organizationCode\x18\x06 \x01(\tR\x10organizationCode\x12\x1a\n" +
	"\bviewType\x18\a \x01(\x05R\bviewType\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12\"\n" +
	"\ftemplateCode\x18\t \x01(\tR\ftemplateCode\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x0e\n" +
	"\x02id\x18\v \x01(\x03R\x02id\x12 \n" +
	"\vprojectCode\x18\f \x01(\tR\vprojectCode\x12\x18\n" +
	"\adeleted\x18\r \x01(\bR\adeleted\x12 \n" +
	"\vcollectType\x18\x0e \x01(\tR\vcollectType\x12\x1a\n" +
	"\btaskCode\x18\x0f \x01(\tR\btaskCode\"\\\n" +
	"\x13SelfProjectResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.project.v1.ProjectR\bprojects\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xcc\x03\n" +
	"\x04Menu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x03R\x03pid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1a\n" +
	"\bfilePath\x18\x06 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12\x12\n" +
	"\x04node\x18\b \x01(\tR\x04node\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1a\n" +
	"\bcreateBy\x18\v \x01(\x03R\bcreateBy\x12\x18\n" +
	"\aisInner\x18\f \x01(\x05R\aisInner\x12\x16\n" +
	"\x06values\x18\r \x01(\tR\x06values\x12\x1e\n" +
	"\n" +
	"showSlider\x18\x0e \x01(\x05R\n" +
	"showSlider\x12\x1e\n" +
	"\n" +
	"statusText\x18\x0f \x01(\tR\n" +
	"statusText\x12\x1c\n" +
	"\tinnerText\x18\x10 \x01(\tR\tinnerText\x12\x18\n" +
	"\afullUrl\x18\x11 \x01(\tR\afullUrl\x12,\n" +
	"\bmenuList\x18\x12 \x03(\v2\x10.project.v1.MenuR\bmenuList\"\xe3\a\n" +
	"\aProject\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x14\n" +
	"\x05Cover\x18\x02 \x01(\tR\x05Cover\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12,\n" +
	"\x11AccessControlType\x18\x05 \x01(\tR\x11AccessControlType\x12\x1c\n" +
	"\tWhiteList\x18\x06 \x01(\tR\tWhiteList\x12\x14\n" +
	"\x05Order\x18\a \x01(\x05R\x05Order\x12\x18\n" +
	"\aDeleted\x18\b \x01(\x05R\aDeleted\x12\"\n" +
	"\fTemplateCode\x18\t \x01(\tR\fTemplateCode\x12\x1a\n" +
	"\bSchedule\x18\n" +
	" \x01(\x01R\bSchedule\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\v \x01(\tR\n" +
	"CreateTime\x12*\n" +
	"\x10OrganizationCode\x18\f \x01(\tR\x10OrganizationCode\x12 \n" +
	"\vDeletedTime\x18\r \x01(\tR\vDeletedTime\x12\x18\n" +
	"\aPrivate\x18\x0e \x01(\x05R\aPrivate\x12\x16\n" +
	"\x06Prefix\x18\x0f \x01(\tR\x06Prefix\x12\x1e\n" +
	"\n" +
	"OpenPrefix\x18\x10 \x01(\x05R\n" +
	"OpenPrefix\x12\x18\n" +
	"\aArchive\x18\x11 \x01(\x05R\aArchive\x12 \n" +
	"\vArchiveTime\x18\x12 \x01(\x03R\vArchiveTime\x12$\n" +
	"\rOpenBeginTime\x18\x13 \x01(\x05R\rOpenBeginTime\x12(\n" +
	"\x0fOpenTaskPrivate\x18\x14 \x01(\x05R\x0fOpenTaskPrivate\x12&\n" +
	"\x0eTaskBoardTheme\x18\x15 \x01(\tR\x0eTaskBoardTheme\x12\x1c\n" +
	"\tBeginTime\x18\x16 \x01(\tR\tBeginTime\x12\x18\n" +
	"\aEndTime\x18\x17 \x01(\tR\aEndTime\x12.\n" +
	"\x12AutoUpdateSchedule\x18\x18 \x01(\x05R\x12AutoUpdateSchedule\x12 \n" +
	"\vProjectCode\x18\x19 \x01(\x03R\vProjectCode\x12\x1e\n" +
	"\n" +
	"MemberCode\x18\x1a \x01(\x03R\n" +
	"MemberCode\x12\x1a\n" +
	"\bJoinTime\x18\x1b \x01(\tR\bJoinTime\x12\x18\n" +
	"\aIsOwner\x18\x1c \x01(\x03R\aIsOwner\x12\x1c\n" +
	"\tAuthorize\x18\x1d \x01(\tR\tAuthorize\x12\x12\n" +
	"\x04code\x18\x1e \x01(\tR\x04code\x12\x1c\n" +
	"\townerName\x18\x1f \x01(\tR\townerName\x12\x1c\n" +
	"\tcollected\x18  \x01(\x05R\tcollected2\xa2\x01\n" +
	"\x0eProjectService\x12>\n" +
	"\x05Index\x12\x18.project.v1.IndexRequest\x1a\x19.project.v1.IndexResponse\"\x00\x12P\n" +
	"\vSelfProject\x12\x1e.project.v1.SelfProjectRequest\x1a\x1f.project.v1.SelfProjectResponse\"\x00B<Z:github.com/Wafer233/msproject-be/api-gateway/proto/projectb\x06proto3"

var (
	file_api_gateway_proto_project_project_proto_rawDescOnce sync.Once
	file_api_gateway_proto_project_project_proto_rawDescData []byte
)

func file_api_gateway_proto_project_project_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_project_project_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_project_project_proto_rawDesc), len(file_api_gateway_proto_project_project_proto_rawDesc)))
	})
	return file_api_gateway_proto_project_project_proto_rawDescData
}

var file_api_gateway_proto_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_gateway_proto_project_project_proto_goTypes = []any{
	(*IndexRequest)(nil),        // 0: project.v1.IndexRequest
	(*IndexResponse)(nil),       // 1: project.v1.IndexResponse
	(*SelfProjectRequest)(nil),  // 2: project.v1.SelfProjectRequest
	(*SelfProjectResponse)(nil), // 3: project.v1.SelfProjectResponse
	(*Menu)(nil),                // 4: project.v1.Menu
	(*Project)(nil),             // 5: project.v1.Project
}
var file_api_gateway_proto_project_project_proto_depIdxs = []int32{
	4, // 0: project.v1.IndexResponse.menuList:type_name -> project.v1.Menu
	5, // 1: project.v1.SelfProjectResponse.projects:type_name -> project.v1.Project
	4, // 2: project.v1.Menu.menuList:type_name -> project.v1.Menu
	0, // 3: project.v1.ProjectService.Index:input_type -> project.v1.IndexRequest
	2, // 4: project.v1.ProjectService.SelfProject:input_type -> project.v1.SelfProjectRequest
	1, // 5: project.v1.ProjectService.Index:output_type -> project.v1.IndexResponse
	3, // 6: project.v1.ProjectService.SelfProject:output_type -> project.v1.SelfProjectResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_project_project_proto_init() }
func file_api_gateway_proto_project_project_proto_init() {
	if File_api_gateway_proto_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_project_project_proto_rawDesc), len(file_api_gateway_proto_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_project_project_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_project_project_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_project_project_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_project_project_proto = out.File
	file_api_gateway_proto_project_project_proto_goTypes = nil
	file_api_gateway_proto_project_project_proto_depIdxs = nil
}
