// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api-gateway/proto/auth/auth_service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------------------------register------------------------------------
type RegisterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterMessage) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *RegisterMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{1}
}

// ------------------------------------login------------------------------------
type LoginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginMessage) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Member           *MemberMessage         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	OrganizationList []*OrganizationMessage `protobuf:"bytes,2,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	TokenList        *TokenMessage          `protobuf:"bytes,3,opt,name=tokenList,proto3" json:"tokenList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetMember() *MemberMessage {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *LoginResponse) GetOrganizationList() []*OrganizationMessage {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

func (x *LoginResponse) GetTokenList() *TokenMessage {
	if x != nil {
		return x.TokenList
	}
	return nil
}

type MemberMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Realname      string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	Account       string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime int64                  `protobuf:"varint,7,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Email         string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMessage) Reset() {
	*x = MemberMessage{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMessage) ProtoMessage() {}

func (x *MemberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMessage.ProtoReflect.Descriptor instead.
func (*MemberMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *MemberMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MemberMessage) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *MemberMessage) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MemberMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberMessage) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *MemberMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MemberMessage) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *MemberMessage) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *MemberMessage) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *MemberMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type OrganizationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberId      int64                  `protobuf:"varint,5,opt,name=memberId,proto3" json:"memberId,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMessage) Reset() {
	*x = OrganizationMessage{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMessage) ProtoMessage() {}

func (x *OrganizationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMessage.ProtoReflect.Descriptor instead.
func (*OrganizationMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *OrganizationMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OrganizationMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *OrganizationMessage) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *OrganizationMessage) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *OrganizationMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrganizationMessage) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *OrganizationMessage) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *OrganizationMessage) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

type TokenMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	TokenType      string                 `protobuf:"bytes,3,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	AccessTokenExp int64                  `protobuf:"varint,4,opt,name=accessTokenExp,proto3" json:"accessTokenExp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenMessage) Reset() {
	*x = TokenMessage{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMessage) ProtoMessage() {}

func (x *TokenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMessage.ProtoReflect.Descriptor instead.
func (*TokenMessage) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *TokenMessage) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenMessage) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenMessage) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenMessage) GetAccessTokenExp() int64 {
	if x != nil {
		return x.AccessTokenExp
	}
	return 0
}

type TokenVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyRequest) Reset() {
	*x = TokenVerifyRequest{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyRequest) ProtoMessage() {}

func (x *TokenVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyRequest.ProtoReflect.Descriptor instead.
func (*TokenVerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *TokenVerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *MemberMessage         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenVerifyResponse) Reset() {
	*x = TokenVerifyResponse{}
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenVerifyResponse) ProtoMessage() {}

func (x *TokenVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_auth_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenVerifyResponse.ProtoReflect.Descriptor instead.
func (*TokenVerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *TokenVerifyResponse) GetMember() *MemberMessage {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_api_gateway_proto_auth_auth_service_proto protoreflect.FileDescriptor

const file_api_gateway_proto_auth_auth_service_proto_rawDesc = "" +
	"\n" +
	")api-gateway/proto/auth/auth_service.proto\x12\x0fauth.service.v1\"\x89\x01\n" +
	"\x0fRegisterMessage\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\acaptcha\x18\x04 \x01(\tR\acaptcha\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x12\n" +
	"\x10RegisterResponse\"D\n" +
	"\fLoginMessage\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xd6\x01\n" +
	"\rLoginResponse\x126\n" +
	"\x06member\x18\x01 \x01(\v2\x1e.auth.service.v1.MemberMessageR\x06member\x12P\n" +
	"\x10organizationList\x18\x02 \x03(\v2$.auth.service.v1.OrganizationMessageR\x10organizationList\x12;\n" +
	"\ttokenList\x18\x03 \x01(\v2\x1d.auth.service.v1.TokenMessageR\ttokenList\"\xb3\x02\n" +
	"\rMemberMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12$\n" +
	"\rlastLoginTime\x18\a \x01(\x03R\rlastLoginTime\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\"\xa9\x02\n" +
	"\x13OrganizationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmemberId\x18\x05 \x01(\x03R\bmemberId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\"\x9a\x01\n" +
	"\fTokenMessage\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\ttokenType\x18\x03 \x01(\tR\ttokenType\x12&\n" +
	"\x0eaccessTokenExp\x18\x04 \x01(\x03R\x0eaccessTokenExp\"*\n" +
	"\x12TokenVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"M\n" +
	"\x13TokenVerifyResponse\x126\n" +
	"\x06member\x18\x01 \x01(\v2\x1e.auth.service.v1.MemberMessageR\x06member2\x86\x02\n" +
	"\vAuthService\x12Q\n" +
	"\bRegister\x12 .auth.service.v1.RegisterMessage\x1a!.auth.service.v1.RegisterResponse\"\x00\x12H\n" +
	"\x05Login\x12\x1d.auth.service.v1.LoginMessage\x1a\x1e.auth.service.v1.LoginResponse\"\x00\x12Z\n" +
	"\vTokenVerify\x12#.auth.service.v1.TokenVerifyRequest\x1a$.auth.service.v1.TokenVerifyResponse\"\x00B:Z8github.com/Wafer233/msproject-be/user-service/proto/authb\x06proto3"

var (
	file_api_gateway_proto_auth_auth_service_proto_rawDescOnce sync.Once
	file_api_gateway_proto_auth_auth_service_proto_rawDescData []byte
)

func file_api_gateway_proto_auth_auth_service_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_auth_auth_service_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_auth_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_auth_auth_service_proto_rawDesc), len(file_api_gateway_proto_auth_auth_service_proto_rawDesc)))
	})
	return file_api_gateway_proto_auth_auth_service_proto_rawDescData
}

var file_api_gateway_proto_auth_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_gateway_proto_auth_auth_service_proto_goTypes = []any{
	(*RegisterMessage)(nil),     // 0: auth.service.v1.RegisterMessage
	(*RegisterResponse)(nil),    // 1: auth.service.v1.RegisterResponse
	(*LoginMessage)(nil),        // 2: auth.service.v1.LoginMessage
	(*LoginResponse)(nil),       // 3: auth.service.v1.LoginResponse
	(*MemberMessage)(nil),       // 4: auth.service.v1.MemberMessage
	(*OrganizationMessage)(nil), // 5: auth.service.v1.OrganizationMessage
	(*TokenMessage)(nil),        // 6: auth.service.v1.TokenMessage
	(*TokenVerifyRequest)(nil),  // 7: auth.service.v1.TokenVerifyRequest
	(*TokenVerifyResponse)(nil), // 8: auth.service.v1.TokenVerifyResponse
}
var file_api_gateway_proto_auth_auth_service_proto_depIdxs = []int32{
	4, // 0: auth.service.v1.LoginResponse.member:type_name -> auth.service.v1.MemberMessage
	5, // 1: auth.service.v1.LoginResponse.organizationList:type_name -> auth.service.v1.OrganizationMessage
	6, // 2: auth.service.v1.LoginResponse.tokenList:type_name -> auth.service.v1.TokenMessage
	4, // 3: auth.service.v1.TokenVerifyResponse.member:type_name -> auth.service.v1.MemberMessage
	0, // 4: auth.service.v1.AuthService.Register:input_type -> auth.service.v1.RegisterMessage
	2, // 5: auth.service.v1.AuthService.Login:input_type -> auth.service.v1.LoginMessage
	7, // 6: auth.service.v1.AuthService.TokenVerify:input_type -> auth.service.v1.TokenVerifyRequest
	1, // 7: auth.service.v1.AuthService.Register:output_type -> auth.service.v1.RegisterResponse
	3, // 8: auth.service.v1.AuthService.Login:output_type -> auth.service.v1.LoginResponse
	8, // 9: auth.service.v1.AuthService.TokenVerify:output_type -> auth.service.v1.TokenVerifyResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_auth_auth_service_proto_init() }
func file_api_gateway_proto_auth_auth_service_proto_init() {
	if File_api_gateway_proto_auth_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_auth_auth_service_proto_rawDesc), len(file_api_gateway_proto_auth_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_auth_auth_service_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_auth_auth_service_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_auth_auth_service_proto_msgTypes,
	}.Build()
	File_api_gateway_proto_auth_auth_service_proto = out.File
	file_api_gateway_proto_auth_auth_service_proto_goTypes = nil
	file_api_gateway_proto_auth_auth_service_proto_depIdxs = nil
}
