server:
  name: "user-service"
  addr: "127.0.0.1:8080"

zap:
  DebugFileName: "C:\\logs\\debug\\project-debug.log"
  InfoFileName:  "C:\\logs\\info\\project-info.log"
  WarnFileName:  "C:\\logs\\error\\project-error.log"
  MaxSize:       500
  MaxAge:        28
  MaxBackups:    3

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

grpc:
  addr: "127.0.0.1:8881"
  name: "user"
  version: "1.0.0"
  weight: 2
