zap:
  DebugFileName: "C:\\logs\\debug\\user-service-debug.log"
  InfoFileName: "C:\\logs\\info\\user-service-info.log"
  WarnFileName: "C:\\logs\\error\\user-service-error.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

mysql:
  host: "localhost"
  port: 3307
  user: "root"
  password: "root"
  dbname: "user-service"

jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: wafer_access_secret
  refreshSecret: wafer_refresh_secret

grpc:
  addr: "127.0.0.1:8080"
  name: "user-service"
  version: "1.0.0"
  weight: 2

metrics:
  enabled: true
  endpoint: "/metrics"
  namespace: "user_service"
